-- Auto Feature Engineering Loop - Schema Setup
-- Creates all Snowflake objects needed for the research loop

CREATE DATABASE IF NOT EXISTS AUTO_FEATURE_ENG;
CREATE SCHEMA IF NOT EXISTS AUTO_FEATURE_ENG.CREDIT_RISK;
USE SCHEMA AUTO_FEATURE_ENG.CREDIT_RISK;

-- Source data: Give Me Some Credit (~150K rows, 11 features + target)
CREATE OR REPLACE TABLE RAW_CREDIT_DATA (
    ID INT,
    SERIOUSDLQIN2YRS INT,
    REVOLVING_UTILIZATION FLOAT,
    AGE INT,
    PAST_DUE_30_59 INT,
    DEBT_RATIO FLOAT,
    MONTHLY_INCOME FLOAT,
    OPEN_CREDIT_LINES INT,
    PAST_DUE_90 INT,
    REAL_ESTATE_LINES INT,
    PAST_DUE_60_89 INT,
    DEPENDENTS FLOAT
);

-- Feature iteration results log
CREATE OR REPLACE TABLE FEATURE_LOG (
    ITERATION_ID INT,
    RUN_ID VARCHAR,
    TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FEATURE_TABLE VARCHAR,
    FEATURES_ADDED VARIANT,
    NUM_FEATURES INT,
    AUC FLOAT,
    KS_STAT FLOAT,
    GINI FLOAT,
    DELTA_AUC FLOAT,
    STATUS VARCHAR,
    STRATEGY VARCHAR,
    REASONING VARCHAR,
    ERROR_MSG VARCHAR
);

-- Cost attribution log
CREATE OR REPLACE TABLE COST_LOG (
    ITERATION_ID INT,
    RUN_ID VARCHAR,
    TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PHASE VARCHAR,
    SDK_COST_USD FLOAT,
    CREDITS_WAREHOUSE FLOAT,
    CREDITS_TOTAL FLOAT,
    SDK_TOKENS_IN INT,
    SDK_TOKENS_OUT INT,
    DURATION_SEC FLOAT
);

-- Internal stage for CSV upload
CREATE OR REPLACE STAGE CREDIT_DATA_STAGE
    FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
